#!/usr/bin/env bash

#############################
# Author: Alejandro Cervera #
# Date: 28/02/22            #
#############################

# Functions
usage() {
    cat << HERE
Description: user(add|del) wrapper script to add or delete multiple users.
Usage: adu <OPERATION> <USER>...

Operations:

    add <USER>
        Add user <USER>.

    delete <USER>
        Delete user <USER>.

    help
        Show script usage.
HERE
}

showError() {
    printf '%b\n' "ERROR: $1" >&2
}

# Constants
readonly USERNAME_MAX_LENGTH=32                                                                                                                                             # Length value source: 'CAVEATS' section in useradd manual.

[[ $# -eq 0 ]] && { showError "No arguments.\n"; usage; exit 1; }

case "$1" in
    ('add')
        shift

        for ARGUMENT in "$@"; do
            # Validate the username.
            if [[ ${#ARGUMENT} -gt ${USERNAME_MAX_LENGTH} ]]; then
                showError "Usernames can not be longer than ${USERNAME_MAX_LENGTH} characters."
                continue
            elif [[ ! "${ARGUMENT}" =~ ^[a-z_][a-z0-9_-]*[$]?$ ]]; then
                showError "Illegal characters found in ${ARGUMENT}'s username!"                                                                                             # Regex based from 'CAVEATS' section in useradd manual. I added the anchors to match only usernames that start and end with pattern.
                continue
            else
                # Add user.
                sudo useradd --create-home "${ARGUMENT}"
            fi
        done
    ;;
    ('delete')
        shift

        # Delete users.
        for username in "$@"; do
             if sudo userdel --remove -- "${username}" &> /dev/null; then
                printf 'Successfully deleted user %s.\n' "${username}"
             else
                showError "Could not delete user \"${username}\"."
             fi
        done
    ;;
    ('help')
        { usage; exit 0; }
    ;;
    (*)
        { showError "Invalid operation \"$1\".\n"; usage; exit 1; }
    ;;
esac
