#!/usr/bin/env bash

#############################
# Author: Alejandro Cervera #
# Date: 21/12/2021          #
#############################
usage(){
    tee << EOF
Description: Empty one or more program's cache and delete old log files.
Usage: ambystoma <DIRECTORY>
EOF
}

printError(){
    printf '%s\n\n' "ERROR: $1" >&2
}

# Constants
readonly CACHE_DIR="${HOME}/.cache" LOG_DIR='/var/log'

[[ $# -eq 0 ]] && { printError "No arguments were given!"; usage; exit 1; }

for ARGUMENT in "$@"; do
    if [[ -z "$(find "${CACHE_DIR}" -type d -name "${ARGUMENT##*/}")" ]]; then                   # Check if the argument is a subdirectory of ~/.cache.     Credits to: Alex Shearn (https://serverfault.com/users/230046/shearn89) for the answer in https://serverfault.com/a/768042
        printError "${ARGUMENT} is not a directory inside ${CACHE_DIR}"
        continue
    else
        rm -ri "${ARGUMENT}"/*                                                                   # Empty directory interactively.
    fi
done

{ echo "Deleting log files..."; sudo find "${LOG_DIR}" -type f -iname "*.old" -delete; }         # Delete log files.
