#!/usr/bin/env bash

#############################
# Author: Alejandro Cervera #
# Date: 21/12/2021          #
#############################
usage() {
    tee << EOF
Description: Empty one or more program's ~/.cache directory.
Usage: ambystoma <DIRECTORY>
EOF
}

printError() {
    printf '%b\n' "$1" >&2
}

trap '{ printError "\nScript was interrupted."; exit 1; }' SIGINT

# Constants
readonly CACHE_DIR="${HOME}/.cache"

[[ $# -eq 0 ]] && { printError "No arguments were given!\n"; usage; exit 1; }

for ARGUMENT in "$@"; do
    directoryBasename="${ARGUMENT##*/}"

    if [[ ! -d "${CACHE_DIR}/${directoryBasename}" ]]; then
        printError "${ARGUMENT} is not a directory inside ${CACHE_DIR}"
        continue
    elif ! find "${CACHE_DIR}/${directoryBasename}" | grep -qvx "${CACHE_DIR}/${directoryBasename}"; then
        printError "${ARGUMENT} is empty, nothing to delete."
        continue
    else
        rm -ri "${ARGUMENT}"/*
    fi
done

trap &> /dev/null
