#!/usr/bin/env bash

#############################
# Author: Alejandro Cervera #
# Date: 23/01/2022          #
#############################

# Functions
usage() {
    local scriptName="${0##*/}"

cat << USAGE
Description: Batch file rename script
Usage: ${scriptName} <PATTERN> <STRING> <FILES>

Example:

${scriptName} FILE file FILE1 FILE2

${scriptName} will rename FILE1 and FILE2 to file1 and file2
(respectively) by replacing pattern "FILE" with "file".

Note:

If the pattern uses wildcards/globs ([], [^], *, ?, etc.), single quote
it to prevent errors with your shell.
USAGE
}

printError() {
    printf "$1\n" >&2
}

trap '{ printError "\nScript was interrupted."; exit 1; }' SIGINT

[[ $# -eq 0 ]] && {
    printError "No arguments\n"

    usage

    exit 1
}

[[ $# -lt 4 ]] && {
    printError "Insufficient arguments\n"

    usage

    exit 1
}


# Arguments.
PATTERN="$1" STRING="$2"

# Rename the files.
shift 2

for ARGUMENT in "$@"; do
    [[ -f "${ARGUMENT}" ]] || {

        printError "Can not rename \"${ARGUMENT}\", it isn't a file."
        continue
    }

    [[ -w "${ARGUMENT}" ]] || {

        printError "Can not rename \"${ARGUMENT}\", it's unwritable."
        continue
    }

    [[ -x "${ARGUMENT%/*}" || -x . ]] || {                                                                          # Credits to user roaima (https://unix.stackexchange.com/users/100397/roaima) for his answer https://unix.stackexchange.com/a/272226 in https://unix.stackexchange.com/questions/272225/minimum-file-permissions-to-rename-file

        printError "Can not rename \"${ARGUMENT}\", parent directory is inaccessible."
        continue
    }

    mv -- "${ARGUMENT}" "${ARGUMENT/$PATTERN/$STRING}" 2>&- || {

        printError "Can not rename \"${ARGUMENT}\", doesn't match pattern \"${PATTERN}\"."
    }
done

trap &> /dev/null
