#!/usr/bin/env bash

#############################
# Author: Alejandro Cervera #
# Date: 21/12/2021          #
#############################

# Functions
usage() {
    local scriptName="${0##*/}"

cat << USAGE
Description: Empty one or more program's ~/.cache directory.
Usage: ${scriptName} <NAME>
USAGE
}

printError() {
    printf "$1\n" >&2
}

readonly CACHE_DIR="${HOME}/.cache"

trap '{ printError "\nScript was interrupted."; exit 1; }' SIGINT

[[ $# -eq 0 ]] && {
    printError "No arguments were given!\n"

    usage

    exit 1
}

# Prompt user for a confirmation before deletion.
shopt -s nocasematch extglob

read -r -p 'Delete contents of subdirectories? [Y/N] '

until [[ "${REPLY}" == @(Y|N|[[:blank:]]) ]]; do
    read -r -p 'Invalid reply to prompt, try again. '
done

[[ "${REPLY}" == N ]] && {

    exit 1
}

# Delete contents.
for ARGUMENT in "$@"; do
    cacheFullPath="${CACHE_DIR}/${ARGUMENT##*/}"

    [[ -e "${cacheFullPath}" ]] || {
        printError "${ARGUMENT} can not be emptied, it does not exist."
        continue
    }

    [[ -d "${cacheFullPath}" ]] || {
        printError "${ARGUMENT} is not a directory inside ${CACHE_DIR}"
        continue
    }

    find "${cacheFullPath}" | grep -qvx -- "${cacheFullPath}" || {
        printError "${ARGUMENT} is empty, nothing to delete."
        continue
    }

    rm -r -- "${cacheFullPath}"/* &> /dev/null
done

trap &> /dev/null
