#!/usr/bin/env bash

printError() {
    printf '%b\n' "$1" >&2
}

trap '{ printError "\nScript was interrupted."; exit 1; }' SIGINT

which pamac &> /dev/null || { printError 'pamac is not installed!' >&2; exit 1; }

ping -c 3 manjaro.org &> /dev/null || {
    printError "Can not check for updates, please check your connection."

    exit 1
}

pamac checkupdates --aur 1>&-

if [[ $? -eq 100 ]]; then
    notify-send 'chk4up' "System updates are available!"
else
    notify-send 'chk4up' "No system updates are available!"
fi

trap &> /dev/null
