#!/usr/bin/env bash
readonly LOGFILE="${HOME}/chk4up.log"

exec 2> "${LOGFILE}"

which pamac &> /dev/null || { echo 'ERROR: pamac is not installed!' >&2; exit 1; }

pamac checkupdates --aur 1>&-

if [[ $? -eq 100 ]]; then
    notify-send 'chk4up' "System updates are available!"
else
    notify-send 'chk4up' "No system updates are available!"
fi
