#!/usr/bin/env bash

# Functions
usage() {
    cat << HERE
Description: youtube-dl wrapper script that reads URLs to download from standard input.
Usage: dl <OPTION> <ARGUMENT>

Available options:

    -a
        Convert downloaded files to an audio format.

    -d DIRECTORY
        Save files in a directory, defaults to /tmp if not specified.

    -h
        Show script usage.

Examples:

dl -a -d ~/Downloads
dl -d ~/Videos
dl -a

HERE
}

showError() {
    printf '%b\n' "$1" >&2
}

download() {
    local failedDownloads=0 URLs

    printf '%s\n\n' "Type the URL(s) to download press Control + D when finished."

    mapfile -t URLs

    [[ ${#URLs} -eq 0 ]] && { showError "No URL(s) to download."; exit 1; }

    for URL in "${URLs[@]}"; do
        if youtube-dl $1 --quiet --no-warnings --no-part --exec "mv {} ${DIRECTORY}" "${URL}" 2>&-; then
            printf 'URL: %s\n' "\"${URL}\" downloaded successfully."
        else
            showError "URL: \"${URL}\" could not be downloaded."
            failedDownloads=$(( failedDownloads+=1 ))
            continue
        fi
    done

    [[ ${#URLs[@]} -eq ${failedDownloads} ]] && { showError "\nNo URL(s) could be downloaded."; exit 1; }
}

readonly DEFAULT_DIR='/tmp'

# Handle interrupts.
trap '{ showError "\nScript was interrupted."; exit 1; }' SIGINT

# Parse options.
optionCount=0

while getopts ':ad:h' OPTION; do
    optionCount=$(( optionCount+=1 ))

    case "${OPTION}" in
        (a)
            convertToAudio='true'
        ;;
        (d)
            DIRECTORY="${OPTARG}"
        ;;
        (h)
            { usage; exit 0; }
        ;;
        ('?')
            { showError "Illegal option -\"${OPTARG}\"."; exit 1; }
        ;;
    esac
done

[[ ${optionCount} -eq 0 ]] && { showError "No options were selected."; exit 1; }

# Assign directory if it was not specified.
DIRECTORY="${DIRECTORY:-$DEFAULT_DIR}"

# Validate directory.
[[ -e "${DIRECTORY}" ]] || { showError "Can not save downloads in directory \"${DIRECTORY}\" it does not exist."; exit 1; }
[[ -d "${DIRECTORY}" ]] || { showError "Can not save downloads in \"${DIRECTORY}\" it is not a directory."; exit 1; }
[[ -w "${DIRECTORY}" ]] || { showError "Can not save downloads in \"${DIRECTORY}\" it does not have write permissions."; exit 1; }

# Download URLs.
if [[ ${convertToAudio} ]]; then
    download '--extract-audio'
else
    download
fi

# Remove traps
trap &> /dev/null
