#!/bin/sh

# Functions
usage() {

cat << USAGE
NAME
        Write a regular file

SYNOPSIS
        ${scriptName} <OPTION> <NAME>

DESCRIPTION
        Use colon shell command ':' and input-output
        redirection to write a file named NAME.

OPTIONS
        --help, -h
            Show script usage

EXAMPLES
        ${scriptName} foo

        ${scriptName} /tmp/apple

        ${scriptName} tux puffy

CAVEATS
        ${scriptName} will fail if executed with the
        friendly interactive shell (fish) since fish
        does not make use of an equals sign (=) when
        assigning values to parameters.

EXIT STATUS
        0
            Script executed successfully.

        64
            Invalid script usage.

        73
            One or more files could not be created.

SEE ALSO
        pathchk(1), touch(1)
USAGE

    # shellcheck disable=SC2086
    exit ${EX_OK}
}

printError() {
    printf "ERROR: $1\n" >&2
}

# Global variables
scriptName="${0##*/}"

# Constants
readonly EX_OK=0 EX_USAGE=64 EX_CANTCREAT=73

# Verify script usage
[ $# -eq 0 ] && {
    printError "No option/argument specified."

    # shellcheck disable=SC2086
    exit ${EX_USAGE}
}

[ "$1" = '--help' ] || [ "$1" = '-h' ] && {
    usage
}

printf '%s\n' "$@" | sort | uniq -d | grep -q '.' && {
    printError "Duplicate file names."

    # shellcheck disable=SC2086
    exit ${EX_USAGE}
}

# Write file(s).
failedWrites=0

for fileName in "$@"; do
    pathchk "${fileName}" 1> /dev/null 2>&1 || {
        printError "Invalid filename \"${fileName}\"."

        failedWrites=$(( failedWrites + 1 ))
        continue
    }

    [ -e "${fileName}" ] && {
        printError "File \"${fileName}\" already exists."

        failedWrites=$(( failedWrites + 1 ))
        continue
    }

    : > "${fileName}" 2>&- || {
        printError "Could not create file."

        failedWrites=$(( failedWrites + 1 ))
        continue
    }

    printf '%s\n' "File \"${fileName}\" created successfully."
done

[ ${failedWrites} -ge 1 ] && {

    exit ${EX_CANTCREAT}
}

exit ${EX_OK}
