#!/usr/bin/env bash

# Copyright 2022 Alejandro Cervera
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

printError() {
    printf "$1\n" >&2
}

trap '{ printError "\n\nScript was interrupted."; exit 1; }' SIGINT

[[ $# -eq 0 ]] && {
    printError "No argument"

    exit 1
}

[[ $# -gt 1 ]] && {
    printError "Too many arguments, only one is required."

    exit 1
}


[[ "$1" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] || {
    printError "\"$1\" is not an IPv4 address."

    exit 1
}

# Loop through the numbers in the address to verify it.
for NUMBER in ${1//./ }; do
    [[ "${NUMBER}" -ge 0 && "${NUMBER}" -le 255 ]] || {
        printError "\"$1\" is not an IPv4 address."

        exit 1
    }
done

printf '%s\n' "$1 is an IPv4 address."

trap &> /dev/null
