#!/usr/bin/env bash

#############################
# Author: Alejandro Cervera #
# Date: 12/03/22            #
#############################
printError() {
    printf '%s\n' "ERROR: $1" >&2
}

if [[ $# -eq 0 ]]; then
    { printError "No argument"; exit 1; }
elif [[ $# -gt 1 ]]; then
    { printError "Too many arguments, only one is required."; exit 1; }
fi

[[ "$1" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] || { printError "\"$1\" is not an IPv4 address."; exit 1; }

# Loop through the numbers in the address to verify it.
for NUMBER in ${1//./ }; do
    [[ "${NUMBER}" -ge 0 && "${NUMBER}" -le 255 ]] || { printError "\"$1\" is not an IPv4 address."; exit 1; }
done

echo "$1 is an IPv4 address."
