#!/usr/bin/env bash

# Copyright (C) 2022 Alejandro Cervera
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA

# Functions
printError() {
    printf "$1\n" >&2
}

# Constants
readonly GREEN="\e[38;5;46m" YELLOW="\e[38;5;226m" BOLD="\e[1m" RESET="\e[0m"

trap '{ printError "\nScript was interrupted."; exit 1; }' SIGINT

# Check for non-system accounts without a password.
shopt -s extglob

printf "Checking accounts...\n\n"

while read -r userAccount; do

    passwordStatus=$(sudo passwd -S "${userAccount}" | cut -d ' ' -f 2)

    case "${passwordStatus}" in
        (NP)
            printf '%b\n' "${BOLD}${YELLOW}WARNING!${RESET} ${userAccount} does not have a password set."
        ;;
        (P?(S))
            printf '%b\n' "${BOLD}${GREEN}OK!${RESET} ${userAccount} has a password set."
        ;;
        (L?(K))
            printf '%b\n' "${BOLD}${GREEN}OK!${RESET} ${userAccount} account is locked."
        ;;
    esac
done < <(sed -r "/nologin|false/d" /etc/passwd | cut -d ':' -f 1)

# Check for package updates and apply them if any are available.
. /etc/os-release

printf "\nChecking for package updates...\n\n"

case "${ID_LIKE:-$ID}" in
    (arch)
        sudo pacman --noconfirm --color always -Syu 2>&-
    ;;
    (debian)
        { sudo apt-get -y update && sudo apt-get -y upgrade; } 2>&-
    ;;
    (fedora)
        # Gets a list of paths to dnf and yum binaries
        packageManagers=("$(type -P dnf yum 2>&-)")

        (( "${#packageManagers[@]}" == 0 )) && {

            printError "No package managers available to check for updates."

            exit 1
        }

        # First package manager available in the system.
        packageManager="${packageManagers[0]##*/}"

        sudo "${packageManager}" -y update
    ;;
    (*)
        printError "Could not check for updates.\n"
    ;;
esac

printf "\nOpen ports:\n\n"; {

    ss -Hutnl | awk '{print $5}' | cut -d : -f 2 | sort -nr | uniq
}

printf "Disk used:\n\n"; {

    df -h / | tail -1 | awk '{print $5}'
}
