#!/usr/bin/env bash

# Copyright (C) 2022 Alejandro Cervera
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA

# Functions
printError() {
    printf "$1\n" >&2
}

# Constants
readonly GREEN="\e[38;5;46m" LIGHT_RED="\e[91m" NORMAL="\e[0m"

trap '{ printError "\nScript was interrupted."; exit 1; }' SIGINT

# Check for non-system accounts without a password.
shopt -s extglob

printf '%s\n' "Checking accounts..."

while read -r userAccount; do

    passwordStatus=$(sudo passwd -S "${userAccount}" | cut -d ' ' -f 2)

    case "${passwordStatus}" in
        (NP)
            printf '%b\n' "${LIGHT_RED}WARNING! ${userAccount} does not have a password set.${NORMAL}"
        ;;
        (P?(S))
            printf '%b\n' "${GREEN}OK! ${userAccount} has a password set.${NORMAL}"
        ;;
        (L?(K))
            printf '%b\n' "${GREEN}OK! ${userAccount} account is locked.${NORMAL}"
        ;;
    esac
done < <(sed -r "/nologin|false/d" /etc/passwd | cut -d ':' -f 1)

# Check for package updates and apply them if any are available.
. /etc/os-release

printf '%b\n' "\nChecking for package updates...\n"

case "${ID_LIKE:-$ID}" in
    (arch)
        sudo pacman --noconfirm --color always -Syu 2>&-
    ;;
    (debian)
        { sudo apt-get -y update && sudo apt-get -y upgrade; } 2>&-
    ;;
    (fedora)
        sudo dnf -y up 2>&- || sudo yum -y update 2>&-
    ;;
    (*)
        printError "Could not check for updates.\n"
    ;;
esac

printf '%b\n' "\nOpen ports:"; {

    ss -Hutnl | awk '{print $5}' | cut -d : -f 2 | sort -nr | uniq
}

{ printf '%s\n' "Disk used:"; df -h / | tail -1 | awk '{print $5}'; }
