#!/bin/bash

#############################
# Author: Alejandro Cervera #
# Date: 05/02/2022          #
#############################

# Global variables
readonly RED="\e[31m" GREEN="\e[32m" YELLOW="\e[33m" BLUE="\e[34m" COLOR_END="\e[0m"                                                                # (Reference: https://dev.to/ifenna__/adding-colors-to-bash-scripts-48g4)

# Functions
welcomeMessage(){
    printf "%b\n\n" "${RED}System information for:${COLOR_END} ${YELLOW}${USER}${COLOR_END}${GREEN}@${COLOR_END}${BLUE}${HOSTNAME}${COLOR_END}"     # Use some rainbow colors in the message.
}

packageCount(){
    local packageManagers=('apt' 'dnf' 'pacman')

    for packageManager in "${packageManagers[@]}"; do
        if which "${packageManager}" &> /dev/null; then                                                                                             # Credits to: ivanleoncz (https://stackoverflow.com/users/5780109) for the answer in https://stackoverflow.com/a/43880464
            case "${packageManager}" in
                (apt)
                    printf 'Packages: %d\n' "$(apt list --installed 2> /dev/null | wc -l)"
                ;;
                (dnf)
                    printf 'Packages: %d\n' "$(dnf list --installed | wc -l)"
                ;;
                (pacman)
                    printf 'Packages: %d\n' "$(pacman -Q | wc -l)"
                ;;
            esac
        else
            continue
        fi
    done
}

getDistribution(){
    local distributionName

    distributionName="$(lsb_release -ds)"

    printf "%s\n" "Distribution: ${distributionName//\"/}"
}

getShell(){
    printf "%s\n" "Shell: ${SHELL#/*/}"
}

welcomeMessage
getShell
packageCount
getDistribution
