#!/usr/bin/env bash

#############################
# Author: Alejandro Cervera #
# Date: 05/02/2022          #
#############################

# Global variables
readonly RED="\e[31m" GREEN="\e[32m" YELLOW="\e[33m" BLUE="\e[34m" COLOR_END="\e[0m"                                                                # (Reference: https://dev.to/ifenna__/adding-colors-to-bash-scripts-48g4)

# Functions
welcomeMessage(){
    printf "%b\n\n" "${RED}System information for:${COLOR_END} ${YELLOW}${USER}${COLOR_END}${GREEN}@${COLOR_END}${BLUE}${HOSTNAME}${COLOR_END}"     # Use some rainbow colors in the message.
}

packageCount(){
    . /etc/os-release

    # Detect distribution.
    case "${ID_LIKE}" in
        (*arch*)
            echo -n "Packages: "; wc -l < <(pacman -Qq)
        ;;
        (*fedora*)
            echo -n "Packages: "; wc -l < <(dnf list --installed) || \
            echo -n "Packages: "; wc -l < <(yum list --installed)                                                                                   # Fallback to yum
        ;;
        (*debian*)
            echo -n "Packages: "; wc -l < <(apt list --installed 2>&-)                                                                              # Silence warnings/errors in apt.
        ;;
        (*)
            echo "Distribution could not be detected"
        ;;
    esac
}

getDistribution(){
    local distributionName

    distributionName="$(lsb_release -ds)"

    printf "%s\n" "Distribution: ${distributionName//\"/}"
}

getShell(){
    printf "%s\n" "Shell: ${SHELL#/*/}"
}

osInfo(){
    local operatingSystem kernelRelease

    # Parse OS name.
    case "${OSTYPE}" in
        (linux-gnu)
            operatingSystem='GNU/Linux'
        ;;
        (*)
            operatingSystem="${OSTYPE}"
        ;;
    esac

    kernelRelease="$(uname -r)"

    printf "%s\n" "OS: ${operatingSystem}" "Kernel: ${kernelRelease}" "Architecture: ${HOSTTYPE}"
}

welcomeMessage
getShell
osInfo
packageCount
getDistribution
