#!/usr/bin/env bash

# Functions
usage() {

cat << USAGE
Description: Pull changes from multiple Git repositories
Usage: ${scriptName} <REPOSITORY>

Examples:

${scriptName} ~/Documents/foo /home/dknuth/bar

${scriptName} "/home/turing/Documents/enigma machine" /home/theo/puffy-bsd
USAGE
}

printError() {
    printf "$1\n" >&2
}

# Locale configuration
unset LANGUAGE LC_ALL

export LC_MESSAGES='en_US.UTF-8'

# Global variable(s)
scriptName="${0##*/}"

# Constants
readonly EX_USAGE=64 EX_UNAVAILABLE=69

TMP_FILE=''

TMP_FILE="$(mktemp --quiet --suffix='.tmp' "${scriptName}".XXXXX)"

declare -r TMP_FILE

# Trap(s)
trap 'rm ${TMP_FILE} &> /dev/null' EXIT

# Verify script usage.
[[ $# -eq 0 ]] && {

    printError "No repositories to pull changes from.\n"

    usage

    exit ${EX_USAGE}
}

failedPulls=0

# shellcheck disable=SC2154
for localRepository in "$@"; do
    [[ -e "${localRepository}" ]] || {

        printError "Repository \"${localRepository}\" does not exist."
        (( failedPulls++ ))
        continue
    }

    [[ -d "${localRepository}" ]] || {

        printError "Repository \"${localRepository}\" is not a directory."
        (( failedPulls++ ))
        continue
    }

    [[ -x "${localRepository}" ]] || {

        printError "Repository's directory \"${localDirectory}\" can not be accessed, please change its permissions."
        (( failedPulls++ ))
        continue
    }

    # Pull changes

    # shellcheck disable=SC2164
    cd "${localRepository}"

    git pull > "${TMP_FILE}" || {

        printError "Could not pull changes from \"${localRepository}\" repository."
        (( failedPulls++ ))
        continue
    }

    grep -qx 'Already up to date.' "${TMP_FILE}" && {

        printf 'Nothing to pull, repository \"%s\" is up to date with all changes.\n' "${localRepository}"
        continue
    }

    printf 'Changes pulled successfully from repository \"%s\".\n' "${localRepository}"
done

[[ $# -eq ${failedPulls} ]] && {

    printError "\nChanges could not be pulled from any repository."
    exit ${EX_UNAVAILABLE}
}

trap &> /dev/null
