#!/usr/bin/env bash

# Functions
usage() {

cat << USAGE
Description: Pull changes from multiple Git repositories
Usage: ${scriptName} <REPOSITORY>

Examples:

${scriptName} ~/Documents/foo /home/dknuth/bar

${scriptName} "/home/turing/Documents/enigma machine" /home/theo/puffy-bsd
USAGE
}

printError() {
    printf "$1\n" >&2
}

# Locale configuration
unset LANGUAGE LC_ALL

export LC_MESSAGES='en_US.UTF-8'

# Global variable(s)
scriptName="${0##*/}"

# Constants
readonly EX_USAGE=64 EX_UNAVAILABLE=69

TMP_FILE=''

TMP_FILE="$(mktemp --quiet --suffix='.tmp' "/tmp/${scriptName}.XXXXX")"

declare -r TMP_FILE

# Trap(s)
trap 'rm "${TMP_FILE}" &> /dev/null' EXIT

# Verify script usage.
[[ $# -eq 0 ]] && {

    printError "[\e[1m\e[38;5;196mERROR\e[0m] No repositories to pull changes from.\n"

    usage

    exit ${EX_USAGE}
}

failedPulls=0

# shellcheck disable=SC2154
for localRepository in "$@"; do
    [[ -e "${localRepository}" ]] || {

        printError "[\e[1m\e[38;5;196mERROR\e[0m] Repository \"${localRepository}\" does not exist."
        (( failedPulls++ ))
        continue
    }

    [[ -d "${localRepository}" ]] || {

        printError "[\e[1m\e[38;5;196mERROR\e[0m] Repository \"${localRepository}\" is not a directory."
        (( failedPulls++ ))
        continue
    }

    [[ -x "${localRepository}" ]] || {

        printError "[\e[1m\e[38;5;196mERROR\e[0m] Repository's directory \"${localRepository}\" is unaccesible."
        (( failedPulls++ ))
        continue
    }

    # Pull changes

    # shellcheck disable=SC2164
    cd "${localRepository}"

    git pull > "${TMP_FILE}" || {

        printError "[\e[1m\e[38;5;196mERROR\e[0m] Could not pull changes from \"${localRepository}\" repository."
        (( failedPulls++ ))
        continue
    }

    grep -qx 'Already up to date.' "${TMP_FILE}" && {

        printf '[\e[1m\e[38;5;255mNOTE\e[0m] Repository \"%s\" is up to date.\n' "${localRepository}"
        continue
    }

    printf '[\e[1m\e[38;5;118mSUCCESS\e[0m] Changes pulled from repository \"%s\".\n' "${localRepository}"
done

[[ $# -eq ${failedPulls} ]] && {

    printError "\n[\e[1m\e[38;5;196mERROR\e[0m] Changes could not be pulled from any repository."
    exit ${EX_UNAVAILABLE}
}

trap &> /dev/null
