#!/usr/bin/env bash

#############################
# Author: Alejandro Cervera #
# Date: 12/02/2022          #
#############################

# Functions
usage() {
    local scriptName="${0##*/}"

cat << USAGE
Description: Add multiple feeds to Newsboat
Usage: ${scriptName} <URL>

Examples:

${scriptName} "http://rss.cnn.com/rss/edition_world.rss" "https://rss.nytimes.com/services/xml/rss/nyt/World.xml"

${scriptName} "https://news.ycombinator.com/rss"
USAGE
}

printError() {
    printf "$1\n" >&2
}

# Global variables.
feedsFile="${HOME}/.newsboat/urls" feeds="$*"

trap '{ printError "\nScript was interrupted."; exit 1; }' SIGINT

[[ $# -eq 0 ]] && { printError "No feeds to add.\n" >&2; usage; exit 1; }
[[ -e "${feedsFile}" ]] || printf '%s\n' "Warning! Feeds file used by Newsboat \"${feedsFile}\" does not exist, it will be created now."

if [[ -s "${feedsFile}" ]]; then
    printf '%s\n' "${feeds// /$'\n'}" >> "${feedsFile}"
else
    printf '%s\n' "${feeds// /$'\n'}" > "${feedsFile}"
fi

trap &> /dev/null
