#!/usr/bin/env bash

#############################
# Author: Alejandro Cervera #
# Date: 12/02/2022          #
#############################
usage() {
    cat << USAGE
Description: Add multiple feeds to Newsboat
Usage: rss <URL>

Examples:

rss "http://rss.cnn.com/rss/edition_world.rss" "https://rss.nytimes.com/services/xml/rss/nyt/World.xml"

rss "https://news.ycombinator.com/rss"
USAGE
}

readonly feedsFile="${HOME}/.newsboat/urls"                                                                                                                 # File which stores the feeds.

[[ $# -gt 0 ]] || { echo "ERROR! Insufficient arguments, please provide one or more feeds as follows: rss \"URL1\"..." >&2; exit 1; }

[[ ! -e "${feedsFile}" ]] && echo "Warning! Feeds file used by Newsboat \"${feedsFile}\" does not exist, it will be created now."

for URL in "$@"; do                                                                                                                                         # Credits to: amertune (https://stackoverflow.com/users/305563/amertune) for the answer in https://stackoverflow.com/a/2581760
    if [[ -s "${feedsFile}" ]]; then
        { echo "Adding feed ${URL} ..."; tee --append "${feedsFile}" <<< "${URL}" > /dev/null; }                                                            # Append to avoid overwriting the feeds file. Credits to: Martin (https://stackoverflow.com/users/119159/martin) for the answer in https://stackoverflow.com/a/4775845
    else
        { echo "Adding feed ${URL}..."; tee "${feedsFile}" <<< "${URL}" > /dev/null; }
    fi
done
