#!/usr/bin/env bash

#############################
# Author: Alejandro Cervera #
# Date: 14/02/22            #
#############################

# Functions
usage() {
    local scriptName="${0##*/}"

    tee << EOF
Usage: ${scriptName} <OPTION> <ARGUMENT>
Description: Backup and restore newsboat feeds and calcurse's data.

Options:

-b NAME
    Create a backup named NAME.

-r PATH
    Restore backup in directory path PATH.

-h
    Show script usage.
EOF
}

printError() {
    printf "$1\n" >&2
}

checkRunning() {
    for programName in "$@"; do
        pgrep -i "${programName}" &> /dev/null && {
             printError "${programName} can not be running while executing this script."
             exit 1
         }
    done
}

# Global variables
newsboatFeeds='feeds.opml' calcurseData='calendarData.ical'

trap '{ printError "\nScript was interrupted."; exit 1; }' SIGINT

# Check dependencies.
which calcurse newsboat &> /dev/null || { printError "calcurse and/or newsboat are not installed, they are required."; exit 1; }

# Parse options.
optionCount=0

while getopts ':b:r:h' OPTION; do
    (( optionCount++ ))

    case "${OPTION}" in
        (b)
            backupName="${OPTARG}"

            backupOption='true'
        ;;
        (r)
            pathToBackup="${OPTARG}"

            restoreOption='true'
        ;;
        (h)
            { usage; exit 0; }
        ;;
        ('?')
            { printError "Unknown option -${OPTARG}!"; exit 1; }
        ;;
        (:)
            { printError "-${OPTARG} option expected an argument!"; exit 1; }
        ;;
    esac
done

[[ ${optionCount} -eq 0 ]] && { printError "No options were specified."; exit 1; }

checkRunning 'calcurse' 'newsboat'

{ "${backupOption:=false}" && "${restoreOption:=false}"; } && { printError "-r and -b options can not be used simultaneously."; exit 1; }

# Create backup.

"${backupOption}" && {
    { newsboat -e > "${newsboatFeeds}"; calcurse -x > "${calcurseData}"; }                                                                    # Export newsboat's and calcurse's data in order to be backed up.

    if tar -c --remove-files -f "${backupName}" "${newsboatFeeds}" "${calcurseData}" &> /dev/null; then
        echo "Backup \"${backupName}\" created successfully!"
        exit 0
    else
        { printError "Could not create backup \"${backupName}\""; exit 1; }
    fi
}

# Restore backup.

"${restoreOption}" && {
    echo "Restoring backup \"${pathToBackup}\"..."

    if tar -xf "${pathToBackup}" &> /dev/null; then                                                                                           # Extract the contents of the backup.
        if { newsboat -i "${newsboatFeeds}"; calcurse -i "${calcurseData}"; }; then
            echo "Backup restored successfully!"
        else
            { printError "Could not restore backup in \"${pathToBackup}\"!"; exit 1; }
        fi
    else
        { printError "Could not restore backup in \"${pathToBackup}\"!"; exit 1; }
    fi
}

trap &> /dev/null
