#!/usr/bin/env bash

#############################
# Author: Alejandro Cervera #
# Date: 25/12/2021          #
#############################

# Functions
printError() {
    printf '%b\n' "$1" >&2
}

# Constants
readonly LIGHT_GREEN="\e[92m" LIGHT_RED="\e[91m" NORMAL="\e[0m"

trap '{ printError "\nScript was interrupted."; exit 1; }' SIGINT

# Check for non-system accounts without a password.
echo "Checking accounts..."

while read -r userAccount; do

    passwordStatus=$(sudo passwd -S "${userAccount}" | cut -d ' ' -f 2)

    case "${passwordStatus}" in
        (NP)
            printf '%b\n' "${LIGHT_RED}WARNING! ${userAccount} does not have a password set.${NORMAL}"
        ;;
        (P|PS)
            printf '%b\n' "${LIGHT_GREEN}OK! ${userAccount} has a password set.${NORMAL}"
        ;;
        (L|LK)
            printf '%b\n' "${LIGHT_GREEN}OK! ${userAccount} account is locked.${NORMAL}"
        ;;
    esac
done < <(sed -r "/nologin|false/d" /etc/passwd | cut -d ':' -f 1)

# Check for package updates and apply them if any are available.
printf '\n%s\n' "What type of distribution are you using:"

select distributionType in "Arch based" "Debian based" "RHEL based"; do
    case "${distributionType}" in
        ('Arch based')
            sudo pacman --noconfirm --color always -Syu
            break
        ;;
        ('Debian based')
            { sudo apt-get -y upgrade && sudo apt-get -y update; }
            break
        ;;
        ('RHEL based')
            sudo dnf -y up || sudo yum -y update
            break
        ;;
    esac
done

# Show open ports.
{ printf '\n%s\n' "Open ports:"; ss -Hutnl | awk '{print $5}' | cut -d : -f 2 | sort -nr | uniq; }

# Show disk usage.
{ echo "Percentage of disk used in root (/) partition:"; df -h / | tail -1 | awk '{print $5}'; }
