#!/usr/bin/env bash

# Functions
usage() {
   local scriptName="${0##*/}"

cat << USAGE
Description: scrot wrapper script.
Usage: ${scriptName} <MODE>

Modes:

    normal  - Take a screenshot of the entire screen.
    grab    - Select a part of a window and take a screenshot of it.
    help    - Show script usage.

The screenshot will be saved in the current working directory.
USAGE
}

printError() {
    printf "$1\n" >&2
}

readonly IMPERIAL_RED='#ED2939'

trap '{ printError "\nScript was interrupted."; exit 1; }' SIGINT

# Check that the user chooses only one mode.
if [[ $# -eq 0 ]]; then
    { printError "No mode selected\n"; usage; exit 1; }
elif [[ $# -gt 1 ]]; then
    { printError "Too many modes selected!\n"; usage; exit 1; }
fi

# Validate mode.
shopt -s extglob

case "$1" in
    (help)
        { usage; exit 0; }
    ;;
    (grab)
        scrot -s -f -l color=${IMPERIAL_RED},width=5 -F 'screenshot-%d-%m-%Y-$wx$h.png' &> /dev/null || { notify-send 'Screenshot was aborted.'; exit 1; }

        notify-send 'Screenshot taken'
    ;;
    (normal)
        scrot -F 'screenshot-%d-%m-%Y-$wx$h.png' &> /dev/null || { notify-send 'Could not take screenshot.'; exit 1; }

        notify-send 'Screenshot taken!'
    ;;
    (+([[:blank:]]) | '')
        { printError "No mode was selected."; exit 1; }
    ;;
    (*)
        { printError "Invalid mode \"$1\".\n"; usage; exit 1; }
    ;;
esac

trap &> /dev/null
