#!/usr/bin/env bash

# Functions
usage() {
   local scriptName="${0##*/}"

cat << USAGE
Description: scrot wrapper script.
Usage: ${scriptName} <MODE>

Modes:

    normal, n  - Take a screenshot of the entire screen.
    grab, g    - Select a part of a window and take a screenshot of it.
    help, h    - Show script usage.

The screenshot will be saved in the current working directory.
USAGE
}

printError() {
    printf "$1\n" >&2
}

readonly IMPERIAL_RED='#ED2939'

trap '{ printError "\nScript was interrupted."; exit 1; }' SIGINT

# Check that the user chooses only one mode.
[[ $# -eq 0 ]] && {
    printError "No mode selected\n"

    usage

    exit 1
}

[[ $# -gt 1 ]] && {
    printError "Too many modes selected!\n"

    usage

    exit 1
}

# Check if there is a configured display.
[[ -z "${DISPLAY}" ]] || {

    printError "No display to take a screenshot of."

    exit 1
}

# Validate mode.
shopt -s extglob

# shellcheck disable=SC2016
case "$1" in
    (h?(elp))
        usage

        exit 0
    ;;
    (g?(rab))
        scrot -s -f -l color=${IMPERIAL_RED},width=5 -F 'screenshot-%d-%m-%Y-$wx$h.png' &> /dev/null || {
            notify-send 'Screenshot was aborted.'

            exit 1
        }

        notify-send 'Screenshot taken'
    ;;
    (n?(ormal))
        scrot -F 'screenshot-%d-%m-%Y-$wx$h.png' &> /dev/null || {
            notify-send 'Could not take screenshot.'

            exit 1
        }

        notify-send 'Screenshot taken!'
    ;;
    (+([[:blank:]]) | '')
        printError "No mode was selected."

        exit 1
    ;;
    (*)
        printError "Invalid mode \"$1\".\n"

        usage

        exit 1
    ;;
esac

trap &> /dev/null
