#!/usr/bin/env bash

# Copyright (C) 2022 Alejandro Cervera
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA

# Functions
usage() {
    local scriptName="${0##*/}"

cat << USAGE
Description: Show information of a process identifier.
Usage: ${scriptName} <OPTION> <PID>

Available options:

    -p PID
        Show the information for process identifier PID.

    -h
        Show script usage.
USAGE
}

printError() {
    printf -- "$1\n" >&2
}

processName() {
    local name=''

    read -r name < "/proc/${PID}/comm"

    printf 'Process: %s\n' "${name}"
}

processStatus() {
    local fileLine

    while read -r fileLine; do
        [[ "${fileLine}" == State:* ]] && {
            # Parse the status.
            prefixRemoved="${fileLine#State:}"
            tabRemoved="${prefixRemoved##$'\t'}"
            letterRemoved="${tabRemoved#[RSDZTItWXxKP]' '}"
            parenthesisRemoved="${letterRemoved//[()]/}"

            printf 'Status: %s\n' "${parenthesisRemoved^}"

            break
        }

    done < <(cat "/proc/${PID}/status")
}

processFDs() {
    local fileDescriptors

    fileDescriptors="$(find "/proc/${PID}/fd" -type l -printf '%f, ' 2>&-)"

    [[ -z "${fileDescriptors}" ]] && {

        printError "File descriptors could not be shown because of a lack of permissions or there weren't any at all"

        return 1
    }

    printf 'Open file descriptors: %s\n' "${fileDescriptors%, }"
}

processCommand() {
    local processCommand

    processCommand="$(tr '\0' ' ' < "/proc/${PID}/cmdline" 2>&-)"

    printf 'Command line: %s\n' "${processCommand%% }"
}

processEnvironment() {
    local processVariables environmentVariables

    processVariables="$(tr '\0' '\n' 2>&- < "/proc/${PID}/environ")"

    environmentVariables=0

    while read -r environmentVariable; do
        [[ -z "${environmentVariable}" ]] && {

            continue
        }

        ((environmentVariables++))
    done <<< "${processVariables}"

    (( ${environmentVariables} == 0 )) && {

        printError "Can not show PID ${PID}'s environment, lacking permissions and/or variables."

        return 1
    }

    printf 'Environment variables:\n\n%s\n' "${processVariables}"
}

trap '{ printError "\nScript was interrupted."; exit 1; }' SIGINT

# Parse options.
optionCount=0

while getopts ':p:h' OPTION; do
    ((optionCount++))

    case "${OPTION}" in
        (p)
            PID="${OPTARG}"
        ;;
        (h)
            usage

            exit 0
        ;;
        (:)
            printError "-${OPTARG} option expected an argument.\n"

            usage

            exit 1
        ;;
        ('?')
            printError "Unknown option \"-${OPTARG}\".\n"

            usage

            exit 1
        ;;
    esac
done

[[ ${optionCount} -eq 0 ]] && {
    printError "No options were selected.\n"

    usage

    exit 1
}

# Validate option argument.
[[ -d "/proc/${PID}" ]] || {
    printError "PID \"${PID}\" does not exist.\n"

    usage

    exit 1
}

# Show PID information.
printf "PID ${PID} information:\n\n"

processName
processStatus
processCommand
processFDs
processEnvironment

trap &> /dev/null
