#!/usr/bin/env bash

# Copyright (C) 2022 Alejandro Cervera
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA

# Functions
usage() {
    local scriptName="${0##*/}"

cat << USAGE
Description: Show information of a process identifier.
Usage: ${scriptName} <OPTION> <PID>

A question mark (?) in the output means ${scriptName} lacked
permissions to get the process's information or there was no
information to show.

Available options:

    -p PID
        Show the information for process identifier PID.

    -h
        Show script usage.

Caveats:

${scriptName} heavily relies on information from proc(5)
and if it is mounted with the hidepid option and has the
values 1 or 2, ${scriptName} might show incomplete or no
output at all.
USAGE
}

printError() {
    printf -- "$1\n" >&2
}

processName() {
    local processName

    read -r processName 2>&- < "/proc/${PID}/comm"

    printf 'Process: %s\n' "${processName:-?}"
}

processStatus() {
    local fileLine

    # Parse the status.
    while read -r fileLine; do
        [[ "${fileLine}" == State:* ]] && {
            processStatus="${fileLine#State:}"

            # Remove tabs at the beginning.
            processStatus="${processStatus##$'\t'}"

            # Remove a space and letter (from the square brackets) at the beginning.
            processStatus="${processStatus#[RSDZTItWXxKP]' '}"

            # Remove parenthesis.
            processStatus="${processStatus//[()]/}"

            # Capitalize first letter.
            processStatus="${processStatus^}"

            printf 'Status: %s\n' "${processStatus:-?}"

            break
        }

    done 2>&- < "/proc/${PID}/status"
}

processFDs() {
    local fileDescriptors

    fileDescriptors="$(find "/proc/${PID}/fd" -type l -printf '%f, ' 2>&-)"

    # Remove trailing comma and space.
    fileDescriptors="${fileDescriptors%, }"

    printf 'Open file descriptors: %s\n\n' "${fileDescriptors:-?}"
}

processCommand() {
    local processCommand

    processCommand="$(tr '\0' ' ' 2>&- < "/proc/${PID}/cmdline")"

    processCommand="${processCommand%% }"

    printf 'Command line: %s\n\n' "${processCommand:-?}"
}

processEnvironment() {
    local processVariables

    processVariables="$(tr '\0' '\n' 2>&- < "/proc/${PID}/environ")"

    printf 'Environment variables:\n\n%s\n\n' "${processVariables:-?}"
}

processOwnership() {

    stat --printf "Ownership of PID ${PID}:\n\nGroup: %G (GID: %g)\tOwner: %U (UID: %u)\n\n" "/proc/${PID}"
}

trap '{ printError "\n\nScript was interrupted."; exit 1; }' SIGINT

# Parse options.
optionCount=0

while getopts ':p:h' OPTION; do
    (( optionCount++ ))

    case "${OPTION}" in
        (p)
            PID="${OPTARG}"
        ;;
        (h)
            usage

            exit 0
        ;;
        (:)
            printError "-${OPTARG} option expected an argument.\n"

            usage

            exit 1
        ;;
        ('?')
            printError "Unknown option \"-${OPTARG}\".\n"

            usage

            exit 1
        ;;
    esac
done

[[ ${optionCount} -eq 0 ]] && {
    printError "No options were selected.\n"

    usage

    exit 1
}

# Validate option argument.
[[ "${PID}" =~ ^[0-9]+$ ]] || {
    printError "PID must be numeric.\n"

    usage

    exit 1
}

[[ -d "/proc/${PID}" ]] || {
    printError "PID \"${PID}\" does not exist.\n"

    usage

    exit 1
}

# Show PID information.
printf "PID ${PID} information:\n\n"

processName
processStatus
processCommand
processOwnership
processFDs
processEnvironment

trap &> /dev/null
