#!/usr/bin/env sh

# modeline vim: et ai ts=4 tw=109

# Copyright 2022 Alejandro Cervera
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

read -r s < /proc/uptime

s=${s%%.*}
m=$(( s / 60 % 60 ))
h=$(( s / 60 / 60 % 60 ))

if [ ${h} -gt 0 ]; then
    if [ ${h} -eq 1 ]; then
        noun='hour'

    else
        noun='hours'

    fi

    if [ ${m} -eq 0 ]; then
        printf '%u %s\n' "${h}" "${noun}"

    elif [ ${m} -eq 1 ]; then
        printf '%u %s, 1 minute\n' "${h}" "${noun}"

    else
        printf '%u %s, %u minutes\n' "${h}" "${noun}" "${m}"

    fi

elif [ ${m} -gt 0 ]; then
    if [ ${m} -eq 1 ]; then
        printf '1 minute\n'

    else
        printf '%u minutes\n' "${m}"

    fi

else
    printf '%u seconds\n' "${s}"

fi
